CREATE TABLE transactions(
  id INTEGER PRIMARY KEY NOT NULL,
  user_id INTEGER NOT NULL,
  type TEXT NOT NULL,
  date DATETIME DEFAULT CURRENT_TIMESTAMP,
  name TEXT NOT NULL,
  symbol TEXT NOT NULL,
  price NUMERIC NOT NULL,
  shares INTEGER NOT NULL,
  FOREIGN KEY(user_id) REFERENCES users(id)
);